### ISSUE TITLE
Some error while running spring boot

### ISSUE THREAD

**Issue by sureshhsrinivas** [alexmihailescu99/shopwebapp#2]
Hey Hi It showing some error in Backend connection can you please help me to resolve that.

**Comment by alexmihailescu99** [comment]
Hi, apologies for the late response, I'm very busy with work and uni at the moment and I'm afraid I can't help you. Note that this app is one of, if not the first app I wrote in Java & Spring and as a result, it is pretty messy. I have another backend repo(called eduwebapp) which is more in line with what a Java & Spring app should look like, which I advise you to check and take as an example if you'd like. It's not 100% how I'd write a backend today, after almost a year work experience, but it's definitely closer to the way it's supposed to be. Best wishes!
